app:
  eureka-server: localhost
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinionLocator: INFO
    root: INFO
server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: product-service
        predicates:
        - Path=/api/v1/product/**
        uri: lb://product-service
      - id: order-service
        predicates:
        - Path=/api/v1/order/**
        - Path=/api/v1/cart/**
        uri: lb://order-service
      - id: inventory-service
        predicates:
        - Path=/api/v1/inventory/**
        uri: lb://inventory-service
      - filters:
        - SetPath=/
        id: service-registry
        predicates:
        - Path=/eureka/web
        uri: http://localhost:8761
      - id: discovery-server-static
        predicates:
        - Path=/eureka/**
        uri: http://localhost:8761
      - id: order-service
        predicates:
        - Path=/api/v1/cart/**
        uri: lb://order-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
