server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/algosneakers
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pass@123
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
